src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdresseRepository::class)
 */
class Adresse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Offres::class, mappedBy="adresse")
     */
    private $offre;

    /**
     * @ORM\ManyToMany(targetEntity=Demandes::class, mappedBy="adresses")
     */
    private $demandes;

    public function __construct()
    {
        $this->offre = new ArrayCollection();
        $this->demandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Offres[]
     */
    public function getOffre(): Collection
    {
        return $this->offre;
    }

    public function addOffre(Offres $offre): self
    {
        if (!$this->offre->contains($offre)) {
            $this->offre[] = $offre;
            $offre->setAdresse($this);
        }

        return $this;
    }

    public function removeOffre(Offres $offre): self
    {
        if ($this->offre->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getAdresse() === $this) {
                $offre->setAdresse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Demandes[]
     */
    public function getDemandes(): Collection
    {
        return $this->demandes;
    }

    public function addDemande(Demandes $demande): self
    {
        if (!$this->demandes->contains($demande)) {
            $this->demandes[] = $demande;
            $demande->addAdress($this);
        }

        return $this;
    }

    public function removeDemande(Demandes $demande): self
    {
        if ($this->demandes->removeElement($demande)) {
            $demande->removeAdress($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->ville;
    }
        
    
}

src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=ImagesRepository::class)
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_image;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\ManyToOne(targetEntity=Offres::class, inversedBy="image")
     */
    private $offre;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="images", cascade={"persist", "remove"})
     */
    private $utilisateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }


    public function getOffre(): ?Offres
    {
        return $this->offre;
    }

    public function setOffre(?Offres $offre): self
    {
        $this->offre = $offre;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

}

src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=OffresRepository::class)
 */
class Offres
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBien::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_bien;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vendeur;

    /**
     * @ORM\ManyToOne(targetEntity=Adresse::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $superficie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_appartements;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_studios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $places_parking;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cave;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_offre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=120)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="offre",cascade={"persist"})
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    public function __construct()
    {
        $this->image = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTypeBien(): ?TypeBien
    {
        return $this->type_bien;
    }

    public function setTypeBien(?TypeBien $type_bien): self
    {
        $this->type_bien = $type_bien;

        return $this;
    }

    public function getVendeur(): ?User
    {
        return $this->vendeur;
    }

    public function setVendeur(?User $vendeur): self
    {
        $this->vendeur = $vendeur;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getNbrePieces(): ?int
    {
        return $this->nbre_pieces;
    }

    public function setNbrePieces(?int $nbre_pieces): self
    {
        $this->nbre_pieces = $nbre_pieces;

        return $this;
    }

    public function getNbreAppartements(): ?int
    {
        return $this->nbre_appartements;
    }

    public function setNbreAppartements(?int $nbre_appartements): self
    {
        $this->nbre_appartements = $nbre_appartements;

        return $this;
    }

    public function getNbreStudios(): ?int
    {
        return $this->nbre_studios;
    }

    public function setNbreStudios(?int $nbre_studios): self
    {
        $this->nbre_studios = $nbre_studios;

        return $this;
    }

    public function getPlacesParking(): ?int
    {
        return $this->places_parking;
    }

    public function setPlacesParking(?int $places_parking): self
    {
        $this->places_parking = $places_parking;

        return $this;
    }

    public function getCave(): ?int
    {
        return $this->cave;
    }

    public function setCave(?int $cave): self
    {
        $this->cave = $cave;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateOffre(): ?\DateTimeInterface
    {
        return $this->date_offre;
    }

    public function setDateOffre(\DateTimeInterface $date_offre): self
    {
        $this->date_offre = $date_offre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(Images $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setOffre($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getOffre() === $this) {
                $image->setOffre(null);
            }
        }

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $numero_telephone;

    /**
     * @ORM\OneToMany(targetEntity=Demandes::class, mappedBy="acheteur", orphanRemoval=true)
     */
    private $demande;

    /**
     * @ORM\OneToMany(targetEntity=Offres::class, mappedBy="vendeur", orphanRemoval=true)
     */
    private $offre;

    
    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\OneToOne(targetEntity=Images::class, mappedBy="utilisateur", cascade={"persist", "remove"})
     */
    private $images;

    public function __construct()
    {
        $this->demande = new ArrayCollection();
        $this->offre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumeroTelephone(): ?string
    {
        return $this->numero_telephone;
    }

    public function setNumeroTelephone(string $numero_telephone): self
    {
        $this->numero_telephone = $numero_telephone;

        return $this;
    }

    /**
     * @return Collection|Demandes[]
     */
    public function getDemande(): Collection
    {
        return $this->demande;
    }

    public function addDemande(Demandes $demande): self
    {
        if (!$this->demande->contains($demande)) {
            $this->demande[] = $demande;
            $demande->setAcheteur($this);
        }

        return $this;
    }

    public function removeDemande(Demandes $demande): self
    {
        if ($this->demande->removeElement($demande)) {
            // set the owning side to null (unless already changed)
            if ($demande->getAcheteur() === $this) {
                $demande->setAcheteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Offres[]
     */
    public function getOffre(): Collection
    {
        return $this->offre;
    }

    public function addOffre(Offres $offre): self
    {
        if (!$this->offre->contains($offre)) {
            $this->offre[] = $offre;
            $offre->setVendeur($this);
        }

        return $this;
    }

    public function removeOffre(Offres $offre): self
    {
        if ($this->offre->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getVendeur() === $this) {
                $offre->setVendeur(null);
            }
        }

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getImages(): ?Images
    {
        return $this->images;
    }

    public function setImages(?Images $images): self
    {
        // unset the owning side of the relation if necessary
        if ($images === null && $this->images !== null) {
            $this->images->setUtilisateur(null);
        }

        // set the owning side of the relation if necessary
        if ($images !== null && $images->getUtilisateur() !== $this) {
            $images->setUtilisateur($this);
        }

        $this->images = $images;

        return $this;
    }
}

templates/offres/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}CONTACTEZ-MOI IMMO OFFRES
{% endblock %}
{% block stylesheets %}
	<style>

		body {
			background-image: url('{{asset("assets/images/profil/city.jpg")}}');
            background-size:cover;
            background-attachment: fixed;
		}
		
        main{
            color:white;
            font-weight: bolder;
            text-shadow:1px 1px 2px black, 0 0 1em blue, 0 0 0.2em blue;
        }

		.btn {
			border-radius: 70px;
            color:white;
            border-color:white;
            text-shadow:1px 1px 2px black, 0 0 1em blue, 0 0 0.2em blue;
		}
        .add-offer{
            color:white;
            text-shadow:1px 1px 2px black, 0 0 1em black, 0 0 0.2em white;
        }
        .hidden{
            display:none;
        }

	</style>
{% endblock %}
{% block titre %}<div class="add-offer"> ...vous êtes vendeur? Ne tardez pas à déposer votre offre..<br> Let's go!</div>{% endblock %}
{% block body %}
	<main class="add-offer">

		<div class="container d-flex" style="padding-left:10px;width:fit-content;">
        	<div class="card" style="padding-left:10px;padding-right:10px;background:transparent;">
				{{ form_start(form) }}

					<label>Titre</label>
					{{ form_widget(form.titre)}}
					<label>Type de biens</label>	
					{{ form_widget(form.typebien)}}
					<label>Superficie en m²</label>
					&nbsp;<label id="result">0</label>
					{{ form_widget(form.superficie,{'attr':{'value':0}})}}
					<div id="app">
					<label>Nombre de pièces</label>
					&nbsp;<label id="result1">0</label>
					{{ form_widget(form.nbre_pieces,{'attr':{'value':0}})}}
					</div>
					<div id="imm">
					<label>Nombre d'appartements</label>
					&nbsp;<label id="result2">0</label>
					{{ form_widget(form.nbre_appartements,{'attr':{'value':0}})}}

					<label>Nombre de studios</label>
					&nbsp;<label id="result3">0</label>
					{{ form_widget(form.nbre_studios,{'attr':{'value':0}})}}
					</div>
					<div id="terr">
					<label>Places de parking</label>
					&nbsp;<label id="result4">0</label>
					{{ form_widget(form.places_parking,{'attr':{'value':0}})}}
					<label>Cave</label>
					&nbsp;<label id="result5">0</label>
					{{ form_widget(form.cave,{'attr':{'value':0}})}}
					</div>
					<label>Prix en €</label>
					&nbsp;<label id="result6">0</label>
					{{ form_widget(form.prix,{'attr':{'value':0}})}}
					<label>Description</label>
					{{ form_widget(form.description)}}
					<label>Ville</label>
					{{ form_widget(form.adresse)}}
                    <label> Ajout d'images</label>
					{{ form_widget(form.image)}}
					<div class="text-center mt-2">
					
					{{ form_widget(form.Valider)}}
					</div>
				{{ form_end(form) }}

			
		</div>
        </div>

	</main>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {	
            let typebiens = document.querySelectorAll(".form-check-input");
			let app = document.querySelector("#app");
			let imm = document.querySelector("#imm");
			let terr = document.querySelector("#terr");
	 		for(let typebien of typebiens){
				typebien.addEventListener('click', function(){
					if(document.getElementById("offres_typebien_3").checked){
	 					app.className = "hidden";
						imm.className = "";
					}else if(document.getElementById("offres_typebien_5").checked || document.getElementById("offres_typebien_6").checked){
						app.className = "hidden";
						imm.className = "hidden";
						terr.className= "hidden";
					}else{
						app.className = "";
						terr.className= "";
	 					imm.className = "hidden";
	 				}	
	 			})
			}

			displayRange("#result","#offres_superficie");
			displayRange("#result1","#offres_nbre_pieces");
			displayRange("#result2","#offres_nbre_appartements");
			displayRange("#result3","#offres_nbre_studios");
			displayRange("#result4","#offres_places_parking");
			displayRange("#result5","#offres_cave");
			displayRange("#result6","#offres_prix");			
	 	}

		function displayRange(id1,id2){
			let results = document.querySelector(id1);
			let ranges = document.querySelectorAll(id2);
			for(let range of ranges){
 				range.addEventListener("input", function(){
					results.innerHTML = range.value;
			 	})
			}
		}
    </script>
{% endblock %}

templates/offres/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CONTACTEZ MOI IMMO OFFRES
{% endblock %}
{% block stylesheets %}
	<style>

		body {
			background-image: url('{{asset("assets/images/profil/exterior.jpg")}}');
			background-size: cover;
			background-attachment: fixed;
		}
		.card {
			background-color: #F4D03F;
			background-image: radial-gradient( circle farthest-corner at 10% 20%,  rgba(0,152,155,1) 0.1%, rgba(0,94,120,1) 94.2% );
			border: 5px solid;
			max-width: 300px;
            max-height:auto;
			border-radius: 10px;
            color:white;
			margin-left:10%;
			margin-right:10%;
			background-attachment:scroll;
		}

		.heading {
			font-weight: 900;
			color: white;

		}

		.hour {
			margin-top: 1px;
			color: white;
			font-size: 12px
		}

		.btn {
			border-radius: 70px;
			color: white;
			border-color: white;
			margin-left: 10px;
		}

		.line-color {
			color: white;
			height: 3px;
		}
		legend {
			color: white;
			text-shadow: 1px 1px 2px black, 0 0 1em white, 0 0 0.2em white;
		}
		.page-link {
			font-size: small
		}
	</style>
{% endblock %}
{% block titre %}
	<span style="text-shadow:1px 1px 2px black, 0 0 1em black, 0 0 0.2em white;">...vous cherchez un bien immobilier? et qui répond à vos attentes?<br>
		vous êtes au bon endroit!</span>
{% endblock %}
{% block body %}
	<main>
		<div class='container text-center'>
			<legend>Vous êtes un vendeur? Déposez votre offre en cliquant sur le bouton ci-dessous :</legend>
			<a type="button" class="btn btn-dark" href="{{path('offre_add')}}">Postez votre offre</a>
		</div>
		<div class="row">
			{% for offre in pagination %}
				<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 mt-5">
					<div class="card p-4">
						<div class="first">
							<h6 class="heading">{{ offre.titre }}</h6>
							<div class="time d-flex flex-row align-items-center justify-content-between mt-3">
								<div class="d-flex align-items-center">
									<span class="hour ml-1">{{ offre.dateOffre | ago }}</span>
								</div>
								<div>
									<span class="font-weight-bold">{{ offre.prix }}
										€</span>
								</div>
							</div>
						</div>
						<hr>
						<div class="second d-flex flex-row mt-2">

							<div class="image mr-3">

									<img src="{{ asset('assets/images/profil/' ~ offre.vendeur.images.urlImage ) }}" class="rounded-circle" width="100" style="border:2px solid white"/>


							</div>

							<div>
								<div class="d-flex flex-row mb-1">
									<span>{{ offre.vendeur.prenom }}
										{{ offre.vendeur.nom }}</span>
								</div>
								<div class="ml-5">
									{% if is_granted("ROLE_ACHETEUR") %}


										<a class="btn btn-outline-dark btn-sm" href="{{ path('offre_detail', {slug: offre.slug}) }}">>>Voir plus</a>

									{% elseif app.user %}


										<span style="font-size:small;margin-left:5px;">Tél:{{ offre.vendeur.numeroTelephone }}</span>
									{% endif %}
								</div>
							</div>
						</div>
						<hr class="line-color">
						<p class="text-left">Zone de recherche :
							<li>
								{{ offre.adresse.ville }}
								{{ offre.adresse.codePostal }}
							</li>
						</p>

					</div>
				</div>
			{% endfor %}

		</div>
		<div class="navigation d-flex justify-content-center my-5">{{ knp_pagination_render(pagination) }}
		</div>
	</main>
{% endblock %}

templates/offres/offre_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}CONTACTEZ-MOI IMMO OFFRES
{% endblock %}
{% block stylesheets %}
	<style>

		body {
			background-image: url('{{asset("assets/images/profil/card.jpg")}}');
			background-size: cover;
			background-attachment: fixed;
		}
		.card {
			background-image: linear-gradient(109.6deg, rgba(15,2,2,1) 11.2%, rgba(36,163,190,1) 91.1%);
			max-width: 55%;
			min-width: 30%;
			height: auto;
			color: white;
			text-align: center;
			padding-bottom: 50px;
			padding-left: 10px;
			padding-right: 10px;
			margin-left: auto;
			margin-right: auto;
			border-radius: 1%;
			border: 5px solid #476875;
			color: whitesmoke;
			text-shadow: 1px 1px 2px black, 0 0 1em gray, 0 0 0.2em white;

		}
		.card img {
			position: relative;
		}

		.heading {
			font-weight: 900;
			color: white;

		}

		.hour {
			margin-top: 1px;
			color: white;
			font-size: 12px;
			text-align: center;
		}

		.btn {
			border-radius: 70px;
			color: white;
			border-color: white;
		}

		.line-color {
			color: green;
			height: 3px;
		}

		.info {
			margin-left: auto;
			margin-right: auto;
			color: white;
			text-shadow: 1px 1px 2px black, 0 0 1em gray, 0 0 0.2em white;
		}
		#desc {
			text-align: left;
			color: whitesmoke;
		}
	</style>
{% endblock %}
{% block titre %}
	<div class="info">et voici les détails...<br></div>
	<div class="info">Let's read it!
	</div>
{% endblock %}
{% block body %}
	<main>
		<div class="d-flex"></div>
			<div class="card col-2 mt-5">
				<span class="hour ml-1">
					Diffusée
					{{ offres.dateOffre | ago }}</span>
				<hr>
				<div>
						<img src="{{ asset('assets/images/profil/' ~ offres.vendeur.images.urlImage ) }}" class="rounded-circle" width="160"/>
					<br>
					{{ offres.vendeur.prenom }}
					{{ offres.vendeur.nom }}
				</div>
				<hr>
				Prix :
				<div>
				<legend>{{ offres.prix}}€</legend>
				</div>
				Type de Bien :
				<div>
					<legend>{{ offres.typeBien }}</legend>
				<div>
					Nombre de Pièce :
				</div>
				<div>
					<legend>{{ offres.nbrePieces }}</legend>
				</div>
				Zone de recherche :
				<div>
					<legend>{{ offres.adresse.ville }}</legend>
				</div>
				<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img src="{{ asset('assets/images/offres/grid.jpg') }}" class="d-block w-100" alt=""/>
						</div>
						{% for image in offres.image %}
							<div class="carousel-item">
								<img src="{{ asset('assets/images/offres/' ~ image.urlImage ) }}" class="d-block w-100" alt=""/>
							</div>
						{% endfor %}
					</div>
					<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
			</div>
			<hr>
			<legend>Description :</legend>
			<div id="desc">{{ offres.description}}</div>
		</div>
	</div>
</main>
{% endblock %}