src/Entity/Demandes.php
<?php

namespace App\Entity;

use App\Entity\TypeBien;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DemandesRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=DemandesRepository::class)
 */
class Demandes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="float")
     */
    private $superficie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_appartements;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_studios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_parking;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cave;

    /**
     * @ORM\Column(type="float")
     */
    private $budget;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_demande;

    /**
     * @gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=120)
     */
    private $slug;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="demande")
     * @ORM\JoinColumn(nullable=false)
     */
    private $acheteur;

    /**
     * @ORM\ManyToMany(targetEntity=Adresse::class, inversedBy="demandes")
     */
    private $adresses;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBien::class, inversedBy="demande")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_bien;




    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    public function __construct()
    {
        
        $this->adresses = new ArrayCollection();
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getNbrePieces(): ?int
    {
        return $this->nbre_pieces;
    }

    public function setNbrePieces(?int $nbre_pieces): self
    {
        $this->nbre_pieces = $nbre_pieces;

        return $this;
    }

    public function getNbreAppartements(): ?int
    {
        return $this->nbre_appartements;
    }

    public function setNbreAppartements(?int $nbre_appartements): self
    {
        $this->nbre_appartements = $nbre_appartements;

        return $this;
    }

    public function getNbreStudios(): ?int
    {
        return $this->nbre_studios;
    }

    public function setNbreStudios(?int $nbre_studios): self
    {
        $this->nbre_studios = $nbre_studios;

        return $this;
    }

    public function getNbreParking(): ?int
    {
        return $this->nbre_parking;
    }

    public function setNbreParking(?int $nbre_parking): self
    {
        $this->nbre_parking = $nbre_parking;

        return $this;
    }

    public function getCave(): ?int
    {
        return $this->cave;
    }

    public function setCave(?int $cave): self
    {
        $this->cave = $cave;

        return $this;
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(float $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDemande(): ?\DateTimeInterface
    {
        return $this->date_demande;
    }

    // public function setDateDemande(\DateTimeInterface $date_demande): self
    // {
    //     $this->date_demande = $date_demande;

    //     return $this;
    // }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    // public function setSlug(string $slug): self
    // {
    //     $this->slug = $slug;

    //     return $this;
    // }


    public function getAcheteur(): ?User
    {
        return $this->acheteur;
    }

    public function setAcheteur(?User $acheteur): self
    {
        $this->acheteur = $acheteur;

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adresse $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses[] = $adress;
        }

        return $this;
    }

    public function removeAdress(Adresse $adress): self
    {
        $this->adresses->removeElement($adress);

        return $this;
    }

    public function getTypeBien(): ?TypeBien
    {
        return $this->type_bien;
    }

    public function setTypeBien(?TypeBien $type_bien): self
    {
        $this->type_bien = $type_bien;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=OffresRepository::class)
 */
class Offres
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBien::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_bien;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vendeur;

    /**
     * @ORM\ManyToOne(targetEntity=Adresse::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $superficie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_appartements;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_studios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $places_parking;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cave;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_offre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=120)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="offre",cascade={"persist"})
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    public function __construct()
    {
        $this->image = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTypeBien(): ?TypeBien
    {
        return $this->type_bien;
    }

    public function setTypeBien(?TypeBien $type_bien): self
    {
        $this->type_bien = $type_bien;

        return $this;
    }

    public function getVendeur(): ?User
    {
        return $this->vendeur;
    }

    public function setVendeur(?User $vendeur): self
    {
        $this->vendeur = $vendeur;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getNbrePieces(): ?int
    {
        return $this->nbre_pieces;
    }

    public function setNbrePieces(?int $nbre_pieces): self
    {
        $this->nbre_pieces = $nbre_pieces;

        return $this;
    }

    public function getNbreAppartements(): ?int
    {
        return $this->nbre_appartements;
    }

    public function setNbreAppartements(?int $nbre_appartements): self
    {
        $this->nbre_appartements = $nbre_appartements;

        return $this;
    }

    public function getNbreStudios(): ?int
    {
        return $this->nbre_studios;
    }

    public function setNbreStudios(?int $nbre_studios): self
    {
        $this->nbre_studios = $nbre_studios;

        return $this;
    }

    public function getPlacesParking(): ?int
    {
        return $this->places_parking;
    }

    public function setPlacesParking(?int $places_parking): self
    {
        $this->places_parking = $places_parking;

        return $this;
    }

    public function getCave(): ?int
    {
        return $this->cave;
    }

    public function setCave(?int $cave): self
    {
        $this->cave = $cave;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateOffre(): ?\DateTimeInterface
    {
        return $this->date_offre;
    }

    public function setDateOffre(\DateTimeInterface $date_offre): self
    {
        $this->date_offre = $date_offre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(Images $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setOffre($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getOffre() === $this) {
                $image->setOffre(null);
            }
        }

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Controller/acheteur/AcheteurdemandesController.php
<?php

namespace App\Controller\acheteur;

use App\Entity\Demandes;
use App\Form\DemandesType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AcheteurdemandesController extends AbstractController
{
    /**
     * @Route("/acheteurdemandes/{acheteur}", name="acheteurdemandes", methods={"GET"}, requirements={"acheteur"="\d+"})
     */
    public function index(Demandes $demandes): Response
    {
     
        return $this->render('acheteurBO/acheteurdemandes/index.html.twig', [
            'controller_name' => 'AcheteurdemandesController',
            'demandes' => $demandes,

           
        ]);
    }

     /**
     * @Route("/acheteurdemandes/add", name="acheteurdemandes_add")
     */
    public function ajoutDemande(Request $request): Response
    {
        $demande = new Demandes();
        $form = $this->createForm(DemandesType::class, $demande);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $demande->setAcheteur($this->getUser());
            $demande->setActif(true);
            $em = $this->getDoctrine()->getManager();
            $em->persist($demande);
            $em->flush();
            return $this->redirectToRoute('demandes');
        }

        return $this->render('acheteurBO/acheteurdemandes/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/acheteurdemandes/tab/{acheteur}", name="acheteur_demandes_bo", methods={"GET"}, requirements={"acheteur"="\d+"})
     */
    public function ActionsDemande(Demandes $demandes): Response
    {
       // $demandes = $this->getDoctrine()->getRepository(Demandes::class)->findBy(['acheteur' => $id]);
       
        return $this->render('acheteurBO/acheteurdemandes/actions.html.twig', [
            'controller_name' => 'AcheteurdemandesController',
            'demandes' => $demandes,
           
        ]);
    }

     /**
     * @Route("/acheteurdemandes/editer/{id}", name="acheteur_demandes_maj", requirements={"id"="\d+"})
     */
    public function MajDemande(Demandes $demandes, Request $request): Response
    {
       // $demandes = $this->getDoctrine()->getRepository(Demandes::class)->findBy(['acheteur' => $id]);
       $form = $this->createForm(DemandesType::class, $demandes);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($demandes);
            $em->flush();
            $this->addFlash('success', 'Votre demande a été modifiée avec succès !');
            return $this->redirectToRoute('acheteur_demandes_bo',[
                'acheteur' => $this->getUser()->getId(),
            ]);
        }
        return $this->render('acheteurBO/acheteurdemandes/maj_demande.html.twig', [
            'form' => $form->createView(),
            'demandes'=>$demandes,
           
        ]);
    }
    
    /**
     * @Route("/acheteurdemandes/activation/{id}", name="acheteur_demandes_activation", requirements={"id"="\d+"})
     */
    public function activerDemande(Demandes $demandes,Request $request): Response
    {
        //dd($demandes);
        $demandes->setActif( ($demandes->getActif()) ? false : true );

        $em = $this->getDoctrine()->getManager();
        $em->persist($demandes);
        $em->flush();
        if($demandes->getActif() === false){
            $this->addFlash('success', 'Votre demande a été désactivée avec succès !');
            }else{
            $this->addFlash('success', 'Votre demande a été activée avec succès !');
            }
            return $this->redirectToRoute('acheteur_demandes_bo',[
                'acheteur' => $this->getUser()->getId(),
            ]);
    }

    /**
     * @Route("/acheteurdemandes/delete/{id}", name="acheteur_demandes_suppression", requirements={"id"="\d+"})
     */
    public function supprimerDemande(Demandes $demandes): Response
    {
        //dd($demandes);
        $em = $this->getDoctrine()->getManager();
        $em->remove($demandes);
        $em->flush();
        $this->addFlash('success', 'Votre demande a été supprimé avec succès !');
        return $this->redirectToRoute('acheteur_demandes_bo',[
            'acheteur' => $this->getUser()->getId(),
        ]);
    }

}

templates/acheteurBO/acheteurdemandes/actions.html.twig
{% extends 'acheteurBO/base.html.twig' %}

{% block title %}CONTACTEZ MOI IMMO MES DEMANDES
{% endblock %}
{% block titre %}MON ESPACE ACHETEUR
{% endblock %}

{% block body %}
	<main>
		<div class="container">
			<h4 class="text-secondary">METTRE A JOUR MES DEMANDES</h4>
			<hr>
			<table class="table table-light table-hover text-dark">
				<thead>
					<tr>
						<th scope="col">
							<h5 class="text-center">Référence</h5>
						</th>
						<th scope="col">
							<h5 class="text-center">Titre</h5>
						</th>
					</tr>
				</thead>
				<tbody>
					{# {{ dump(demandes)}} #}
					{% for demande in app.user.demande %}

						<tr>
							<td class="text-center">#Ref000{{ demande.id }}</td>

							<td class="text-center">{{ demande.titre }}</td>
						</tr>
						<tr>
							<td colspan="2" class="text-center">
								<a class="btn btn-sm btn-outline-success" href="{{ path('acheteur_demandes_maj',{id:demande.id})}}">Editer</a>
								{% if demande.actif == 1 %}
									<a class="btn btn-sm btn-outline-dark" href="{{ path('acheteur_demandes_activation',{id:demande.id})}}">Archiver</a>
								{% else %}
									<a class="btn btn-sm btn-dark" href="{{ path('acheteur_demandes_activation',{id:demande.id})}}">Publier</a>
								{% endif %}
								<a class="btn btn-outline-danger btn-sm modal-trigger" data-bs-toggle="modal" data-bs-target="#modalDelete" data-id="{{ demande.id }}" data-reference="{{ demande.id }}">Supprimer</a>
							</td>
						</tr>

					{% endfor %}

				</tbody>
			</table>
		</div>
	</main>
	<!-- Modal -->
	<div class="modal fade" id="modalDelete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Supprimer une demande</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					...
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
					<a href="" class="btn btn-primary">Supprimer</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script>
		window.onload = () => {
let btdeletes = document.querySelectorAll(".modal-trigger")
for (let btdelete of btdeletes) {
btdelete.addEventListener("click", function () {
document.querySelector(".modal-footer a").href = `/acheteurdemandes/delete/${
this.dataset.id
}`
document.querySelector(".modal-body").innerText = `Êtes-vous sûr de vouloir supprimer la demande #REF000${
this.dataset.reference
} ?`
})
}
}
	</script>
{% endblock %}

templates/acheteurBO/acheteurdemandes/add.html.twig
{% extends 'acheteurBO/base.html.twig' %}

{% block title %}
	CONTACTEZ-MOI IMMO DEMANDES
{% endblock %}
{% block stylesheets %}
	<style>
		.hidden {
			display: none;
		}
	</style>
{% endblock %}
{% block titre %}MON ESPACE ACHETEUR
{% endblock %}
{% block body %}
	<main>
		<div class="container">
			<h4 class="text-secondary">POSTER UNE DEMANDE</h4>
			<hr>
			<div class="container">
				<div class="row">
					{{ form_start(form) }}
					<table>
						<tbody>
							<tr>
								<th>Titre:</th>
								<td>{{ form_widget(form.titre) }}</td>
							</tr>
							<tr>
								<th>Type du bien:</th>
								<td>{{ form_widget(form.typebien) }}</td>
							</tr>
							<tr>
								<th>Superficie:
								</th>
								<td>{{ form_widget(form.superficie,{'attr':{'value':0}}) }}
								</td>
								<td>&nbsp;<span id="result">0</span>m²&nbsp;</td>
							</tr>
							<tr class="app">
								<th>Nombre de Pièces:
								</th>
								<td>{{ form_widget(form.nbre_pieces,{'attr':{'value':0}}) }}</td>
								<td>&nbsp;<span id="result1">0&nbsp;</span>
								</td>
							</tr>
							<tr class="imm">
								<th>Nombre d'Appartements:</th>
								<td>{{ form_widget(form.nbre_appartements,{'attr':{'value':0}}) }}</td>
								<td>
									&nbsp;<span id="result2">0&nbsp;</span>
								</td>
							</tr>
							<tr class="imm1">
								<th>Nombre de Studios:</th>
								<td>{{ form_widget(form.nbre_studios,{'attr':{'value':0}}) }}</td>
								<td>&nbsp;<span id="result3">0&nbsp;</span>
								</td>
							</tr>
							<tr class="terr">
								<th>Places de Parking:
								</th>
								<td>{{ form_widget(form.nbre_parking,{'attr':{'value':0}}) }}</td>
								<td>&nbsp;<span id="result4">0&nbsp;</span>
								</td>
							</tr>
							<tr class="terr1">
								<th>Cave:
								</th>
								<td>{{ form_widget(form.cave,{'attr':{'value':0}}) }}</td>
								<td>&nbsp;<span id="result5">0</span>&nbsp;</td>
							</tr>
							<tr>
								<th>Budget:
								</th>
								<td>{{ form_widget(form.budget,{'attr':{'value':0}}) }}</td>
								<td>&nbsp;<span id="result6">0</span>€&nbsp;</td>
							</tr>
							<tr>
								<th>Description:</th>
								<td>{{ form_widget(form.description) }}</td>
							</tr>
							<tr>
								<th>Zone de recherche:</th>
								<td>{{ form_widget(form.adresses) }}</td>
							</tr>
							<tr>
								<th></th>
								<td class="text-center">{{ form_widget(form.Valider,{Label:"Mettre à jour"}) }}</td>
							</tr>
						</tbody>
					</table>

					{{ form_end(form) }}
				</div>
			</div>
		</div>
	</main>
{% endblock %}

{% block javascripts %}
	<script>
		window.onload = () => {
let typebiens = document.querySelectorAll(".form-check-input");
let app = document.querySelector(".app");
let imm = document.querySelector(".imm");
let terr = document.querySelector(".terr");
let imm1 = document.querySelector(".imm1");
let terr1 = document.querySelector(".terr1");
for (let typebien of typebiens) {
typebien.addEventListener('click', function () {
if (document.getElementById("demandes_typebien_3").checked) {
app.className = "hidden";
imm.className = "";
imm1.className = "";
} else if (document.getElementById("demandes_typebien_5").checked || document.getElementById("demandes_typebien_6").checked) {
app.className = "hidden";
imm.className = "hidden";
imm1.className = "hidden";
terr.className = "hidden";
terr1.className = "hidden";
} else {
app.className = "";
terr.className = "";
terr1.className = "";
imm.className = "hidden";
imm1.className = "hidden";
}
})
}

displayRange("#result", "#demandes_superficie");
displayRange("#result1", "#demandes_nbre_pieces");
displayRange("#result2", "#demandes_nbre_appartements");
displayRange("#result3", "#demandes_nbre_studios");
displayRange("#result4", "#demandes_nbre_parking");
displayRange("#result5", "#demandes_cave");
displayRange("#result6", "#demandes_budget");
}

function displayRange(id1, id2) {
let results = document.querySelector(id1);
let ranges = document.querySelectorAll(id2);
for (let range of ranges) {
range.addEventListener("input", function () {
results.innerHTML = range.value;
})
}
}
	</script>
{% endblock %}

templates/acheteurBO/acheteurdemandes/maj_demande.html.twig
{% extends 'acheteurBO/base.html.twig' %}

{% block title %}
	CONTACTEZ-MOI IMMO DEMANDES
{% endblock %}
{% block stylesheets %}
	<style>
		.hidden {
			display: none;
		}
	</style>
{% endblock %}
{% block titre %}MON ESPACE ACHETEUR
{% endblock %}
{% block body %}
	<main>
		<div class="container">
			<h4 class="text-secondary">EDITER UNE DEMANDE</h4>
			<hr>
			<div class="container">
				<div class="row">
					{{ form_start(form) }}
					<table>
						<tbody>
							<tr>
								<th>Titre:</th>
								<td>{{ form_widget(form.titre) }}</td>
							</tr>
							<tr>
								<th>Type du bien:</th>
								<td>{{ form_widget(form.typebien) }}</td>
							</tr>
							<tr>
								<th>Superficie:
								</th>
								<td>{{ form_widget(form.superficie) }}
								</td>
								<td>&nbsp;<span id="result">{{ demandes.superficie }}</span>m²&nbsp;</td>
							</tr>
							<tr class="app">
								<th>Nombre de Pièces:
								</th>
								<td>{{ form_widget(form.nbre_pieces) }}</td>
								<td>&nbsp;<span id="result1">{{ demandes.nbrePieces }}&nbsp;</span>
								</td>
							</tr>
							<tr class="imm">
								<th>Nombre d'Appartements:</th>
								<td>{{ form_widget(form.nbre_appartements) }}</td>
								<td>
									&nbsp;<span id="result2">{{ demandes.nbreAppartements }}&nbsp;</span>
								</td>
							</tr>
							<tr class="imm1">
								<th>Nombre de Studios:</th>
								<td>{{ form_widget(form.nbre_studios) }}</td>
								<td>&nbsp;<span id="result3">{{ demandes.nbreStudios }}&nbsp;</span>
								</td>
							</tr>
							<tr class="terr">
								<th>Places de Parking:
								</th>
								<td>{{ form_widget(form.nbre_parking) }}</td>
								<td>&nbsp;<span id="result4">{{ demandes.nbreParking }}&nbsp;</span>
								</td>
							</tr>
							<tr class="terr1">
								<th>Cave:
								</th>
								<td>{{ form_widget(form.cave) }}</td>
								<td>&nbsp;<span id="result5">{{ demandes.cave }}</span>&nbsp;</td>
							</tr>
							<tr>
								<th>Prix:
								</th>
								<td>{{ form_widget(form.budget) }}</td>
								<td>&nbsp;<span id="result6">{{ demandes.budget }}</span>€&nbsp;</td>
							</tr>
							<tr>
								<th>Description:</th>
								<td>{{ form_widget(form.description) }}</td>
							</tr>
							<tr>
								<th>Zone de recherche:</th>
								<td>{{ form_widget(form.adresses) }}</td>
							</tr>
							<tr>
								<th></th>
								<td class="text-center">{{ form_widget(form.Valider,{Label:"Mettre à jour"}) }}</td>
							</tr>
						</tbody>
					</table>

					{{ form_end(form) }}
				</div>
			</div>
		</div>
	</main>
{% endblock %}

{% block javascripts %}
	<script>
		window.onload = () => {
let typebiens = document.querySelectorAll(".form-check-input");
let app = document.querySelector(".app");
let imm = document.querySelector(".imm");
let terr = document.querySelector(".terr");
let imm1 = document.querySelector(".imm1");
let terr1 = document.querySelector(".terr1");
for (let typebien of typebiens) {
typebien.addEventListener('click', function () {
if (document.getElementById("demandes_typebien_3").checked) {
app.className = "hidden";
imm.className = "";
imm1.className = "";
} else if (document.getElementById("demandes_typebien_5").checked || document.getElementById("demandes_typebien_6").checked) {
app.className = "hidden";
imm.className = "hidden";
imm1.className = "hidden";
terr.className = "hidden";
terr1.className = "hidden";
} else {
app.className = "";
terr.className = "";
imm.className = "hidden";
imm1.className = "hidden";
}
})
}

displayRange("#result", "#demandes_superficie");
displayRange("#result1", "#demandes_nbre_pieces");
displayRange("#result2", "#demandes_nbre_appartements");
displayRange("#result3", "#demandes_nbre_studios");
displayRange("#result4", "#demandes_nbre_parking");
displayRange("#result5", "#demandes_cave");
displayRange("#result6", "#demandes_budget");
}

function displayRange(id1, id2) {
let results = document.querySelector(id1);
let ranges = document.querySelectorAll(id2);
for (let range of ranges) {
range.addEventListener("input", function () {
results.innerHTML = range.value;
})
}
}
	</script>
{% endblock %}