src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=ImagesRepository::class)
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_image;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\ManyToOne(targetEntity=Offres::class, inversedBy="image")
     */
    private $offre;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="images", cascade={"persist", "remove"})
     */
    private $utilisateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }


    public function getOffre(): ?Offres
    {
        return $this->offre;
    }

    public function setOffre(?Offres $offre): self
    {
        $this->offre = $offre;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?User $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

}

src/Entity/Offres.php
<?php

namespace App\Entity;

use App\Repository\OffresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ORM\Entity(repositoryClass=OffresRepository::class)
 */
class Offres
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBien::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_bien;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vendeur;

    /**
     * @ORM\ManyToOne(targetEntity=Adresse::class, inversedBy="offre")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\Column(type="float")
     */
    private $superficie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_pieces;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_appartements;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbre_studios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $places_parking;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cave;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $date_offre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=120)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="offre",cascade={"persist"})
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    public function __construct()
    {
        $this->image = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTypeBien(): ?TypeBien
    {
        return $this->type_bien;
    }

    public function setTypeBien(?TypeBien $type_bien): self
    {
        $this->type_bien = $type_bien;

        return $this;
    }

    public function getVendeur(): ?User
    {
        return $this->vendeur;
    }

    public function setVendeur(?User $vendeur): self
    {
        $this->vendeur = $vendeur;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->adresse;
    }

    public function setAdresse(?Adresse $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getNbrePieces(): ?int
    {
        return $this->nbre_pieces;
    }

    public function setNbrePieces(?int $nbre_pieces): self
    {
        $this->nbre_pieces = $nbre_pieces;

        return $this;
    }

    public function getNbreAppartements(): ?int
    {
        return $this->nbre_appartements;
    }

    public function setNbreAppartements(?int $nbre_appartements): self
    {
        $this->nbre_appartements = $nbre_appartements;

        return $this;
    }

    public function getNbreStudios(): ?int
    {
        return $this->nbre_studios;
    }

    public function setNbreStudios(?int $nbre_studios): self
    {
        $this->nbre_studios = $nbre_studios;

        return $this;
    }

    public function getPlacesParking(): ?int
    {
        return $this->places_parking;
    }

    public function setPlacesParking(?int $places_parking): self
    {
        $this->places_parking = $places_parking;

        return $this;
    }

    public function getCave(): ?int
    {
        return $this->cave;
    }

    public function setCave(?int $cave): self
    {
        $this->cave = $cave;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateOffre(): ?\DateTimeInterface
    {
        return $this->date_offre;
    }

    public function setDateOffre(\DateTimeInterface $date_offre): self
    {
        $this->date_offre = $date_offre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(Images $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image[] = $image;
            $image->setOffre($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getOffre() === $this) {
                $image->setOffre(null);
            }
        }

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }
}

src/Controller/vendeur/VendeurOffresController.php
<?php

namespace App\Controller\vendeur;

use App\Entity\Images;
use App\Entity\Offres;
use App\Form\ImagesType;
use App\Form\OffresType;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class VendeurOffresController extends AbstractController
{
    /**
     * @Route("/vendeur/offres/{vendeur}", name="vendeur_offres", methods={"GET"}, requirements={"vendeur"="\d+"})
     */
    public function index(Offres $offres): Response
    {
        return $this->render('vendeurBO/vendeur_offres/index.html.twig', [
            
            'offres' => $offres,
        ]);
    }

    /**
     * @Route("/vendeur/offres/add", name="vendeur_offres_add")
     */
    public function ajoutOffre(Request $request): Response
    {
        $offres = new Offres();
        $form = $this->createForm(OffresType::class, $offres);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $offres->setVendeur($this->getUser());
            $offres->setActif(true);
            // On récupère les images transmises
            $images = $form->get('image')->getData();
    
            // On boucle sur les images
            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()).'.'.$image->guessExtension();
        
                // On copie le fichier dans le dossier uploads
                $image->move(
                $this->getParameter('images_directory'),
                $fichier
                );
        
                // On crée l'image dans la base de données
                $image = new Images();
                $image->setUrlImage($fichier);
                $offres->addImage($image);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($offres);
            $em->flush();
            return $this->redirectToRoute('vendeur');
        }

        return $this->render('vendeurBO/vendeur_offres/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

     /**
     * @Route("/vendeur/offres/actions/{vendeur}", name="vendeur_offres_actions", methods={"GET"}, requirements={"vendeur"="\d+"})
     */
    public function ActionsOffre(Offres $offres): Response
    {
       // $offres = $this->getDoctrine()->getRepository(Offres::class)->findBy(['vendeur' => $id]);
       
        return $this->render('vendeurBO/vendeur_offres/actions.html.twig', [
            'offres' => $offres,
           
        ]);
    }

     /**
     * @Route("/vendeur/offres/editer/{id}", name="vendeur_offres_maj", requirements={"id"="\d+"})
     */
    public function MajOffre(Offres $offres, Request $request): Response
    {
       $form = $this->createForm(OffresType::class, $offres);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmises
            $images = $form->get('image')->getData();
    
            // On boucle sur les images
            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()).'.'.$image->guessExtension();
        
                // On copie le fichier dans le dossier uploads
                $image->move(
                $this->getParameter('images_directory'),
                $fichier
                );
        
                // On crée l'image dans la base de données
                $img = new Images();
                $img->setUrlImage($fichier);
                $offres->addImage($img);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($offres);
            $em->flush();
            $this->addFlash('success', 'Votre offre a été modifiée avec succès !');
            //$referer = $request->headers->get('referer');
            // dd($this->getUser()->getId());
            return $this->redirectToRoute('vendeur_offres_actions',[
                'vendeur' => $this->getUser()->getId(),
            ]);
        }
        return $this->render('vendeurBO/vendeur_offres/maj_offre.html.twig', [
            'form' => $form->createView(),
            'offres' => $offres,
           
        ]);
    }

    /**
     * @Route("/vendeur/offres/activation/{id}", name="vendeur_offres_activation", requirements={"id"="\d+"})
     */
    public function activerOffre(Offres $offres, Request $request): Response
    {
        //dd($offres);
        $offres->setActif( ($offres->getActif()) ? false : true );

        $em = $this->getDoctrine()->getManager();
        $em->persist($offres);
        $em->flush();
        if($offres->getActif() === false){
        $this->addFlash('success', 'Votre offre a été désactivée avec succès !');
        }else{
        $this->addFlash('success', 'Votre offre a été activée avec succès !');
        }
        return $this->redirectToRoute('vendeur_offres_actions',[
            'vendeur' => $this->getUser()->getId(),
        ]);
       
    }

     /**
     * @Route("/vendeur/offres/suppression/{id}", name="vendeur_offres_suppression", requirements={"id"="\d+"})
     */
    public function supprimerOffre(Offres $offres,Request $request): Response
    {   
        foreach($offres->getImage() as $image){
            $offres->removeImage($image);
        }
        
        //dd($offres);
        $em = $this->getDoctrine()->getManager();
        $em->remove($offres);
        $em->flush();
        $this->addFlash('success', 'Votre offre a été supprimé avec succès !');
        return $this->redirectToRoute('vendeur_offres_actions',[
            'vendeur' => $this->getUser()->getId(),
        ]);
    }

    /**
     * @Route("/vendeur/offres/image/{id}", name="vendeur_offres_edit_image", requirements={"id"="\d+"})
     */
    public function imageOffre(Images $images, Request $request): Response
    {
        //dd($offres);
        $form = $this->createForm(ImagesType::class, $images);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmises
            $imgs = $form->get('url_image')->getData();
    
            // On boucle sur les images
            foreach($imgs as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()).'.'.$image->guessExtension();
        
                // On copie le fichier dans le dossier uploads
                $image->move(
                $this->getParameter('images_directory'),
                $fichier
                );
        
                // On crée l'image dans la base de données
                $images->setUrlImage($fichier);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($images);
            $em->flush();
        
            $this->addFlash('success', 'Votre image a été mise à jour avec succès !');
        }

        
        return $this->render('vendeurBO/vendeur_offres/edit_image.html.twig',[
            'form' =>$form->createView(),
            'images' =>$images,
        ]);
       
    }

    /**
     * @Route("/vendeur/offres/images/{offre}", name="vendeur_offres_image", requirements={"offre"="\d+"})
     */
    public function editImageOffre(Images $images, Request $request): Response
    {
        return $this->render('vendeurBO/vendeur_offres/maj_images.html.twig',[
            'images' =>$images,
        ]);
    }

}

templates/vendeurBO/vendeur_offres/actions.html.twig
{% extends 'vendeurBO/base.html.twig' %}

{% block title %}CONTACTEZ MOI IMMO MES OFFRES{% endblock %}
{% block titre %}MON ESPACE VENDEUR{% endblock %}

{% block body %}
    <main>
        <div class = "container">
            <div class="h4">
            METTRE A JOUR MES OFFRES
            </div>
            <hr>
            <table class="table table-warning table-hover text-warning">
                <thead>
                    <tr>
                        <th scope="col">
                            <h5 class="text-dark">Référence</h5>
                        </th>
                        <th scope="col">
                            <h5 class="text-dark">Titre</h5>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for offre in app.user.offre %}
                    <tr>
                        <td>
                            <h6 class="text-dark">#Ref000{{ offre.id }}</h6>
                        </td>
      
                        <td>
                            <h6 class="text-dark">{{ offre.titre }}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="9" class="text-left text-center">
                            <a class="btn btn-sm btn-outline-success"href="{{ path('vendeur_offres_maj',{id:offre.id})}}">Editer</a>
                            {% if offre.actif == 1 %}
                            <a class="btn btn-sm btn-outline-dark"href="{{ path('vendeur_offres_activation',{id:offre.id})}}">Archiver</a>
                            {% else %}
                            <a class="btn btn-sm btn-dark"href="{{ path('vendeur_offres_activation',{id:offre.id})}}">Publier</a>
                            {% endif %}
                            <a class="btn btn-sm btn-outline-success"href="{{ path('vendeur_offres_image',{offre:offre.id})}}">Gérer les images</a>
                            <a class="btn btn-outline-danger btn-sm modal-trigger" data-bs-toggle="modal" data-bs-target="#modalDelete" data-id="{{ offre.id }}" data-reference="{{ offre.id }}">Supprimer</a>
                        </td>
                    </tr>

                    {% endfor %}

                </tbody>
            </table>
        </div>
    </main>

<!-- Modal -->
    <div class="modal fade" id="modalDelete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Supprimer une offre</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <a href="" class="btn btn-primary">Supprimer</a>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {
            let btdeletes = document.querySelectorAll(".modal-trigger")
            for(let btdelete of btdeletes) {
                btdelete.addEventListener("click", function(){
                    document.querySelector(".modal-footer a").href=`/vendeur/offres/suppression/${this.dataset.id}`
                    document.querySelector(".modal-body").innerText = `Êtes-vous sûr de vouloir supprimer la demande #REF000${this.dataset.reference} ?`
                })
            }
        }
    </script>
{% endblock %}

templates/vendeurBO/vendeur_offres/edit_image.html.twig
{% extends 'vendeurBO/base.html.twig' %}

{% block title %} CONTACTEZ-MOI IMMO OFFRES {% endblock %}
{% block stylesheets %}
<style>
.hidden{
	display:none;
}
</style>
{% endblock %}
{% block titre %}MON ESPACE VENDEUR{% endblock %}
{% block body %}
	<main>
        <div class="container">
            <div class="h4">
                Mettre à jour mes images
            </div>
            <hr>
            <div class="container">
                <div class="card">
					<img src="{{ asset('assets/images/offres/' ~ images.urlImage ) }}" class="d-block w-70" alt=""/></a>                
                </div>
                {{ form(form) }}
               
            </div>
        </div>
	</main>
{% endblock %}

templates/vendeurBO/vendeur_offres/index.html.twig
{% extends 'vendeurBO/base.html.twig' %}

{% block title %}CONTACTEZ MOI IMMO MES OFFRES{% endblock %}
{% block titre %}MON ESPACE VENDEUR{% endblock %}
{% block body %}
<main>
<div class = "container">
<div class="h4">VOIR MES OFFRES</div>
<hr>
<div class="accordion" id="accordionExample">

{% for offre in offres.vendeur.offre %}
  
   <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ offre.id }}">
      <button class="accordion-button text-warning bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ offre.id }}" aria-expanded="true" aria-controls="collapse{{ offre.id }}">
        #Ref000{{ offre.id }} : {{ offre.titre }}
      </button>
    </h2>
    <div id="collapse{{ offre.id }}" class="accordion-collapse collapse show" aria-labelledby="heading{{ offre.id }}" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      {{ offre.description }}
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{ asset('assets/images/offres/grid.jpg') }}" class="d-block w-50" alt=""/>
          </div>
          {% for image in offres.image %}
            <div class="carousel-item">
              <img src="{{ asset('assets/images/offres/' ~ image.urlImage ) }}" class="d-block w-50" alt=""/>
            </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      </div>
    </div>
  </div>
 {% endfor %}

</div>
</div>
</main>
{% endblock %}

templates/vendeurBO/vendeur_offres/maj_images.html.twig
{% extends 'vendeurBO/base.html.twig' %}

{% block title %} CONTACTEZ-MOI IMMO OFFRES {% endblock %}
{% block stylesheets %}
<style>
.hidden{
	display:none;
}
</style>
{% endblock %}
{% block titre %}MON ESPACE VENDEUR{% endblock %}
{% block body %}
	<main>
        <div class="container">
            <div class="h4">
                Mettre à jour mes images
            </div>
            <hr>
            <div class="container">
                
                <div class="row">
                    {% for image in images.offre.image %}
                    <div class="card" style="width: 18rem;height: auto">                          
                        <div class="">
                            <a href="{{ path('vendeur_offres_edit_image', {id: image.id}) }}"><img src="{{ asset('assets/images/offres/' ~ image.urlImage ) }}" width="100%" alt=""/></a>
                        </div>
                    </div>
                    {% endfor %}					
                </div>
                
            </div>
        </div>
	</main>
{% endblock %}

templates/vendeurBO/vendeur_offres/maj_offre.html.twig
{% extends 'vendeurBO/base.html.twig' %}

{% block title %} CONTACTEZ-MOI IMMO OFFRES {% endblock %}
{% block stylesheets %}
<style>
.hidden{
	display:none;
}
</style>
{% endblock %}
{% block titre %}MON ESPACE VENDEUR{% endblock %}
{% block body %}
	<main>
    <div class="container">
    <div class="h4">EDITER UNE OFFRE</div>
					<hr>
		<div class="container">
    <div class="row">
        {{ form_start(form) }}
        <table>
            <tbody>
            <tr>
                <th>Titre:</th>
                <td>{{ form_widget(form.titre) }}</td>
            </tr>
             <tr>
                <th>Type du bien:</th>
                <td>{{ form_widget(form.typebien) }}</td>
            </tr>
            <tr>
                <th>Superficie: </th>
                <td>{{ form_widget(form.superficie) }} </td>
                <td>&nbsp;<span id="result">{{ offres.superficie }}</span>m²&nbsp;</td>
            </tr>
            <tr class="app">
                <th>Nombre de Pièces: </th>
                <td>{{ form_widget(form.nbre_pieces) }}</td>
                <td>&nbsp;<span id="result1">{{ offres.nbrePieces }}&nbsp;</span></td>
            </tr>
			<tr class="imm">
                <th>Nombre d'Appartements:</th>
                <td>{{ form_widget(form.nbre_appartements) }}</td>
                <td> &nbsp;<span id="result2">{{ offres.nbreAppartements }}&nbsp;</span></td>
            </tr>
			<tr class="imm1">
                <th>Nombre de Studios:</th>
                <td>{{ form_widget(form.nbre_studios) }}</td>
                <td>&nbsp;<span id="result3">{{ offres.nbreStudios }}&nbsp;</span></td>
            </tr>
            <tr class="terr">
                <th>Places de Parking: </th>
                <td>{{ form_widget(form.places_parking) }}</td>
                <td>&nbsp;<span id="result4">{{ offres.placesParking }}&nbsp;</span></td>
            </tr>
            <tr class="terr1">
                <th>Cave: </th>
                <td>{{ form_widget(form.cave) }}</td>
                <td>&nbsp;<span id="result5">{{ offres.cave }}</span>&nbsp;</td>
            </tr>
            <tr>
                <th>Prix: </th>
                <td>{{ form_widget(form.prix) }}</td>
                <td>&nbsp;<span id="result6">{{ offres.prix }}</span>€&nbsp;</td>
            </tr>
            <tr>
                <th>Description:</th>
                <td>{{ form_widget(form.description) }}</td>
            </tr>
            <tr>
                <th>Ville:</th>
                <td>{{ form_widget(form.adresse) }}</td>
            </tr>
			<tr>
                <th>Vos images en pièces-jointes:</th>
                <td>{{ form_widget(form.image) }}</td>
            </tr>
            <tr >
                <th></th>
                <td class="text-center">{{ form_widget(form.Valider,{Label:"Mettre à jour"}) }}</td>
            </tr>
            </tbody>
        </table>
		
        {{ form_end(form) }}
    </div>
    </div>
	</main>
{% endblock %}

{% block javascripts %}
    <script>
        window.onload = () => {	
            let typebiens = document.querySelectorAll(".form-check-input");
			let app = document.querySelector(".app");
			let imm = document.querySelector(".imm");
			let terr = document.querySelector(".terr");
            let imm1 = document.querySelector(".imm1");
			let terr1 = document.querySelector(".terr1");
	 		for(let typebien of typebiens){
				typebien.addEventListener('click', function(){
					if(document.getElementById("offres_typebien_3").checked){
	 					app.className = "hidden";
						imm.className = "";
                        imm1.className = "";
					}else if(document.getElementById("offres_typebien_5").checked || document.getElementById("offres_typebien_6").checked){
						app.className = "hidden";
						imm.className = "hidden";
                        imm1.className = "hidden";
						terr.className= "hidden";
                        terr1.className= "hidden";
					}else{
						app.className = "";
						terr.className= "";
	 					imm.className = "hidden";
                        imm1.className = "hidden";
	 				}	
	 			})
			}

			displayRange("#result","#offres_superficie");
			displayRange("#result1","#offres_nbre_pieces");
			displayRange("#result2","#offres_nbre_appartements");
			displayRange("#result3","#offres_nbre_studios");
			displayRange("#result4","#offres_places_parking");
			displayRange("#result5","#offres_cave");
			displayRange("#result6","#offres_prix");			
	 	}

		function displayRange(id1,id2){
			let results = document.querySelector(id1);
			let ranges = document.querySelectorAll(id2);
			for(let range of ranges){
 				range.addEventListener("input", function(){
					results.innerHTML = range.value;
			 	})
			}
		}
    </script>
{% endblock %}